name: 🏭 PURE FORENSIC Builder

on:
  workflow_dispatch:

jobs:
  Build_Spy_Module:
    runs-on: macos-latest
    timeout-minutes: 6

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🧽 Clean CRLF
        run: |
          brew install dos2unix
          dos2unix Makefile control Tweak.xm || true

      - name: 🍺 Install Theos Dependencies
        run: |
          export HOMEBREW_NO_AUTO_UPDATE=1
          brew install dpkg ldid

      - name: ⚙️ Setup Theos
        run: |
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV
          git clone --recursive https://github.com/theos/theos.git $HOME/theos

      - name: 🔍 Compile Pure Spyware
        run: |
          export THEOS=$HOME/theos
          export PATH=$THEOS/bin:$PATH
          export CODESIGN_ALLOCATE=/usr/bin/true
          export THEOS_DEVICE_IP=""
          
          make package FINALPACKAGE=1 messages=yes

      - name: 🚀 Deliver Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Outlaw_Spy_HUD
          path: packages/
